### ISSUE TITLE
Issue with "Map": An abnormal situation occurred .

### ISSUE THREAD

**Issue by masx200** [mdn/translated-content#4906] opened 2022-03-31 00:01 UTC
MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map

#### What information was incorrect, unhelpful, or incomplete?

![Screenshot_2022-03-31-07-57-31-286_com android chrome](https://user-images.githubusercontent.com/34191203/160949783-5b9b417b-5d67-425b-837f-89420ff75d2e.jpg)

```
[属性](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map#%E5%B1%9E%E6%80%A7_2)
{{page('zh-CN/Web/JavaScript/Reference/Global_Objects/Map/prototype','属性')}}

[方法](https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map#%E6%96%B9%E6%B3%95)
{{page('zh-CN/Web/JavaScript/Reference/Global_Objects/Map/prototype','方法')}}

```
#### Specific section or headline?
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map#%E5%B1%9E%E6%80%A7_2

#### What did you expect to see?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#instance_properties
#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `zh-cn/web/javascript/reference/global_objects/map`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Map
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/javascript/reference/global_objects/map/index.html
* Last commit: https://github.com/mdn/translated-content/commit/d44f5032d0f53256b2d5aef505d6b593fd3cd158
* Document last modified: 2022-02-15T18:35:54.000Z

</details>

**Comment by SphinxKnight** [comment] 2022-03-31 04:31
linking to https://github.com/mdn/translated-content/issues/3893

**Comment by cw118** [comment] 2022-03-31 04:35
(N.B. this is also a duplicate of #3680)

**Comment by cw118** [comment] 2022-04-03 14:45
Closing since this is a duplicate of #3680 (and cf. The issue linked above)

**Closed** 2022-04-03 14:45 UTC
Labels: duplicate, l10n-zh
