### ISSUE TITLE
Issue with "JavaScript モジュール": Broken hyper-links to js-examples

### ISSUE THREAD

**Issue by shingoitoh** [mdn/translated-content#5780] opened 2022-05-23 03:07 UTC
MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Modules

#### What information was incorrect, unhelpful, or incomplete?
Maybe resouce is moved.

before:
  https://github.com/mdn/js-examples/tree/master/modules

current:
  https://github.com/mdn/js-examples/tree/master/module-examples

#### Did you test this? If so, how?

<details>
<summary>Page report details</summary>

* Folder: `ja/web/javascript/guide/modules`
* MDN URL: https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Modules
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ja/web/javascript/guide/modules/index.html
* Last commit: https://github.com/mdn/translated-content/commit/e3b342c94fc0a3be0864839452184f80c76f0a4c
* Document last modified: 2022-05-18T13:05:43.000Z

</details>

**Comment by tramio** [comment] 2022-05-31 20:36
Greetings 👋🏻 

The issue is exactly the same as #5800 (which concerns the French translation of the same _JavaScript Modules_ page), which was fixed by #5861.

The task: update 21 URLs (all links to MDN GitHub repositories / files) and 2 code snippets that broke following the renaming of a directory ([commit #a5ca9cdfafd1a684e8a7d317df14bd39171f031c](https://github.com/mdn/js-examples/commit/a5ca9cdfafd1a684e8a7d317df14bd39171f031c)).

May I have this issue assigned? 😄

**Comment by cw118** [comment] 2022-05-31 20:45
@tramio Thanks for taking care of this! Assigned to you, your PR will be reviewed by the `ja` team :)

**Closed** 2022-06-06 01:57 UTC
Labels: l10n-ja
