### ISSUE TITLE
Proposition of translation of footer for French doc

### ISSUE THREAD

**Issue by tisma95** [mdn/translated-content#14080] opened 2023-07-07 15:58 UTC
### MDN URL

https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting

### What specific section or headline is this issue about?

Missing translation of footer

### What information was incorrect, unhelpful, or incomplete?

Found a content problem with this page?
[Edit the page on GitHub](https://github.com/mdn/translated-content/edit/main/files/fr/learn/html/introduction_to_html/advanced_text_formatting/index.md).
[Report the content issue](https://github.com/mdn/translated-content/issues/new?template=page-report-fr.yml&mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Ffr%2Fdocs%2FLearn%2FHTML%2FIntroduction_to_HTML%2FAdvanced_text_formatting&metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EPage+report+details%3C%2Fsummary%3E%0A%0A*+Folder%3A+%60fr%2Flearn%2Fhtml%2Fintroduction_to_html%2Fadvanced_text_formatting%60%0A*+MDN+URL%3A+https%3A%2F%2Fdeveloper.mozilla.org%2Ffr%2Fdocs%2FLearn%2FHTML%2FIntroduction_to_HTML%2FAdvanced_text_formatting%0A*+GitHub+URL%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Ftranslated-content%2Fblob%2Fmain%2Ffiles%2Ffr%2Flearn%2Fhtml%2Fintroduction_to_html%2Fadvanced_text_formatting%2Findex.md%0A*+Last+commit%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Ftranslated-content%2Fcommit%2F621efa84e357b811772d146adc5fee98b82f186f%0A*+Document+last+modified%3A+2023-06-08T17%3A04%3A23.000Z%0A%0A%3C%2Fdetails%3E).
[View the source on GitHub](https://github.com/mdn/translated-content/blob/main/files/fr/learn/html/introduction_to_html/advanced_text_formatting/index.md?plain=1).
Want to get more involved? [Learn how to contribute](https://github.com/mdn/content/blob/main/CONTRIBUTING.md).
This page was last modified on 8 juin 2023 by [MDN contributors](https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting/contributors.txt).

### What did you expect to see?

Vous avez constaté un problème de contenu sur cette page ?
[Modifier la page sur GitHub](https://github.com/mdn/translated-content/edit/main/files/fr/learn/html/introduction_to_html/advanced_text_formatting/index.md).
[Signaler un problème de contenu](https://github.com/mdn/translated-content/issues/new?template=page-report-fr.yml&mdn-url=https%3A%2F%2Fdeveloper.mozilla.org%2Ffr%2Fdocs%2FLearn%2FHTML%2FIntroduction_to_HTML%2FAdvanced_text_formatting&metadata=%3C%21--+Do+not+make+changes+below+this+line+--%3E%0A%3Cdetails%3E%0A%3Csummary%3EPage+report+details%3C%2Fsummary%3E%0A%0A*+Folder%3A+%60fr%2Flearn%2Fhtml%2Fintroduction_to_html%2Fadvanced_text_formatting%60%0A*+MDN+URL%3A+https%3A%2F%2Fdeveloper.mozilla.org%2Ffr%2Fdocs%2FLearn%2FHTML%2FIntroduction_to_HTML%2FAdvanced_text_formatting%0A*+GitHub+URL%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Ftranslated-content%2Fblob%2Fmain%2Ffiles%2Ffr%2Flearn%2Fhtml%2Fintroduction_to_html%2Fadvanced_text_formatting%2Findex.md%0A*+Last+commit%3A+https%3A%2F%2Fgithub.com%2Fmdn%2Ftranslated-content%2Fcommit%2F621efa84e357b811772d146adc5fee98b82f186f%0A*+Document+last+modified%3A+2023-06-08T17%3A04%3A23.000Z%0A%0A%3C%2Fdetails%3E).
[Voir la source sur GitHub](https://github.com/mdn/translated-content/blob/main/files/fr/learn/html/introduction_to_html/advanced_text_formatting/index.md?plain=1).
Vous souhaitez vous impliquer davantage ? [Apprenez comment contribuer](https://github.com/mdn/content/blob/main/CONTRIBUTING.md).
Cette page a été modifiée le 8 juin 2023 par [Les contributeurs MDN](https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting/contributors.txt).

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/learn/html/introduction_to_html/advanced_text_formatting`
* MDN URL: https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Advanced_text_formatting
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/learn/html/introduction_to_html/advanced_text_formatting/index.md
* Last commit: https://github.com/mdn/translated-content/commit/621efa84e357b811772d146adc5fee98b82f186f
* Document last modified: 2023-06-08T17:04:23.000Z

</details>

**Comment by yin1999** [comment] 2023-07-12 01:58
Duplicate of #6943

**Closed by yin1999** 2023-07-12 01:58 UTC
Labels: duplicate, l10n-fr
