### ISSUE TITLE
the Chinese translation of the callback of requestAnimationFrame are not correct

### ISSUE THREAD

**Issue by tszbstzm** [mdn/translated-content#22087] opened 2024-07-01 04:46 UTC
### MDN URL

https://developer.mozilla.org/zh-CN/docs/Web/API/Window/requestAnimationFrame

### 哪些信息是错误、无用或不完善的？

The English version and the Chinese version of the article have completely opposite meanings at this point.
The English version says the _timestamp_ and _performance.now_ are similar but not same, while the Chinese version says they are same.

![image](https://github.com/mdn/translated-content/assets/55863682/4a7a79d8-06bc-4f1f-8f2d-b413fac4571c)

![image](https://github.com/mdn/translated-content/assets/55863682/8bd10d45-07f5-4c1b-97b8-da54376d0353)

And I think compared with the English version, the Chinese version lacks a lot of content. Maybe I can translate a new version of Web APIs/Window/requestAnimationFrame.

### 你期望看到什么？

Correct Chinese translation of the callback parameter of requestAnimationFrame.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `zh-cn/web/api/window/requestanimationframe`
* MDN URL: https://developer.mozilla.org/zh-CN/docs/Web/API/Window/requestAnimationFrame
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/zh-cn/web/api/window/requestanimationframe/index.md
* Last commit: https://github.com/mdn/translated-content/commit/204728a544bf76f0313d8563d643d37b1d25204c
* Document last modified: 2024-05-25T06:37:05.000Z

</details>

**Comment by yin1999** [comment] 2024-07-01 05:07
> Maybe I can translate a new version of Web APIs/Window/requestAnimationFrame.

Welcome PRs for it :)

**Comment by jasonren0403** [comment] 2024-07-30 02:53
close, as the issue is resolved by #22324

**Closed by jasonren0403** 2024-07-30 02:53 UTC
Labels: l10n-zh
