### ISSUE TITLE
Problem with img

### ISSUE THREAD

**Issue by LucienLassalle** [mdn/translated-content#12293] opened 2023-03-20 15:29 UTC
### MDN URL

https://developer.mozilla.org/fr/docs/Web/CSS/object-fit

### What specific section or headline is this issue about?

result

### What information was incorrect, unhelpful, or incomplete?

img doesn't appear on the website

### What did you expect to see?

img

### Do you have any supporting links, references, or citations?

/

### Do you have anything more you want to share?

/

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/css/object-fit`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/CSS/object-fit
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/css/object-fit/index.md
* Last commit: https://github.com/mdn/translated-content/commit/79faa1509d68be77f14971a843e43da59dedff2f
* Document last modified: 2022-09-21T09:43:31.000Z

</details>

**Comment by yarusome** [comment] 2023-03-21 03:20
Duplicate of #12130 and #12105.

**Comment by yin1999** [comment] 2023-03-21 06:38
> Duplicate of #12130 and #12105. See also [mdn/yari#5652](https://github.com/mdn/yari/issues/5652).

Closing this issue in favour of #12130.

**Closed by yin1999** 2023-03-21 06:38 UTC
Labels: duplicate, l10n-fr
