### ISSUE TITLE
translation error

### ISSUE THREAD

**Issue by wandrey7** [mdn/translated-content#20729] opened 2024-05-22 19:20 UTC
### MDN URL

https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Guide/Typed_arrays

### What specific section or headline is this issue about?

Buffers

### What information was incorrect, unhelpful, or incomplete?

Link not formatted correctly, only the text appears without the link. The error is present in the Brazilian Portuguese translation, in English it appears correctly
![image](https://github.com/mdn/translated-content/assets/152204812/032e9be7-a390-494b-a041-3d98103e1096)

### What did you expect to see?

A table with data

**Comment by yin1999** [comment] 2024-05-23 01:26
Hey @wandrey7. This issue should be a part of #3899. I'm going to close this, as it's a duplicate of #3899.

**Closed by yin1999** 2024-05-23 01:26 UTC
Labels: l10n-pt-br

**Comment by wandrey7** [comment] 2024-05-23 18:53
> Hey @wandrey7. This issue should be a part of #3899. I'm going to close this, as it's a duplicate of #3899.

ok
