### ISSUE TITLE
Issue with "Приоритет операторов": (short summary here please)

### ISSUE THREAD

**Issue by Rnbsov** [mdn/translated-content#4585] opened 2022-03-13 11:34 UTC
MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

#### What information was incorrect, unhelpful, or incomplete?
Неправильный приоритет операторов начиная с yield

#### Specific section or headline?
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table

#### What did you expect to see?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence#table

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/javascript/reference/operators/operator_precedence`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Operator_Precedence
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/javascript/reference/operators/operator_precedence/index.html
* Last commit: https://github.com/mdn/translated-content/commit/ba8d3f6f9d418e3b7fdfe79ccfb6e7a6ffb7f566
* Document last modified: 2022-03-12T00:12:34.000Z

</details>

**Comment by cw118** [comment] 2022-03-13 14:46
Thank you for reporting @Rnbsov! It looks like this issue is part of/a duplicate of #3470, so I'll be closing this.

**Closed by cw118** 2022-03-13 14:46 UTC
Labels: duplicate, l10n-ru
