### ISSUE TITLE
各个模块侧边导航栏不能滑动展示

### ISSUE THREAD

**Issue by blueKieron** [mdn/translated-content#12424] opened 2023-03-27 03:17 UTC
![image](https://user-images.githubusercontent.com/48239113/227832332-2ef5eede-9fbf-4f95-804c-047a54a8567b.png)
缺少```overflow:auto;```

**Comment by yin1999** [comment] 2023-03-27 04:40
Duplicate of mdn/yari#8494.

This is a platform issue. I'm going to close this.

**Closed by yin1999** 2023-03-27 04:40 UTC
