### ISSUE TITLE
Issue with "500 Internal Server Error": (When I click 'History' on some files, Server Error 500 appears.)

### ISSUE THREAD

**Issue by tkguswls1106** [mdn/translated-content#6222] opened 2022-06-11 14:44 UTC
MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/Status/500

#### What information was incorrect, unhelpful, or incomplete?
When I click 'History' on some files, Server Error 500 appears. One example is 'History' from 'TIL-SHJ_ver./기타/백준 ps 필기.txt'.

#### Specific section or headline?
One example is 'History' from 'TIL-SHJ_ver./기타/백준 ps 필기.txt'.

#### What did you expect to see?
My file's 'History'

#### Did you test this? If so, how?
Server Error 500

<details>
<summary>Page report details</summary>

* Folder: `ko/web/http/status/500`
* MDN URL: https://developer.mozilla.org/ko/docs/Web/HTTP/Status/500
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ko/web/http/status/500/index.html
* Last commit: https://github.com/mdn/translated-content/commit/a8374c38ecd0e96b9c310da2e3808d9669524581
* Document last modified: 2021-06-23T13:46:42.000Z

</details>

**Comment by cw118** [comment] 2022-06-11 14:46
Hi @tkguswls1106, could you please specify what the issue is with this MDN page? This repo is unfortunately not the place to ask for help with code.

**Comment by tkguswls1106** [comment] 2022-06-11 15:02
In the 'Server Error 500' window, a written statement appears at the bottom, and the History does not open.

Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

**Comment by tkguswls1106** [comment] 2022-06-11 15:03
@cw118 

In the Server Error 500 window, a written statement appears at the bottom, and the History does not open.

Looks like something went wrong!
We track these errors automatically, but if the problem persists feel free to contact us. In the meantime, try refreshing.

**Comment by cw118** [comment] 2022-06-11 15:07
Thank you for responding. However, I'm not sure how this is connected to any *problems on the MDN page you specified*, which just gives the definition of a 500 HTTP error.

**Comment by tkguswls1106** [comment] 2022-06-11 15:12
@cw118 

I'm still a beginner developer, so I don't know what MDN is. Maybe that's why I posted the wrong article here. I apologise if that is the case.

**Comment by cw118** [comment] 2022-06-11 15:16
MDN Web Docs is a website that has documentation of web technologies such as HTTP and JavaScript. This repository has the files for translations of the website and issues created here should tell us about any problems (e.g. typos, mistakes, etc.) that you faced while reading a page on the website. I will close this for now because *this repository is not for asking code questions*. 

If I misunderstood and there is a problem with the Korean page on the 500 HTTP error, please let me know and we can reopen this :)

**Closed** 2022-06-11 15:16 UTC
Labels: l10n-ko
