### ISSUE TITLE
Lists of available elements are empty

### ISSUE THREAD

**Issue by StephaneP43** [mdn/translated-content#12590] opened 2023-04-06 10:16 UTC
### MDN URL

https://developer.mozilla.org/fr/docs/Web/HTML/Element

### What specific section or headline is this issue about?

all sections (except svg section)

### What information was incorrect, unhelpful, or incomplete?

In the french version of this page, all tables are empty whatever the section, instead of containing a list of elements with their description.

The only working section is this one : https://developer.mozilla.org/fr/docs/Web/HTML/Element#svg_et_mathml
All other sections are empty.

### What did you expect to see?

Each section of this page should list according elements like the english version https://developer.mozilla.org/en-US/docs/Web/HTML/Element
By example, in the metadata section (US version), we can see `<base>` description, `<head>` description, etc...

### Do you have anything more you want to share?

Example of missing elements data :
![mdn-elements-fr](https://user-images.githubusercontent.com/48241710/230347803-0ab14bb7-3746-44a6-a87a-62d4b3997c48.png)

**Comment by cw118** [comment] 2023-04-06 21:21
Thanks for the report @StephaneP43 ! I will close this issue since it is a duplicate of #11953, we are working on fixing this on all pages :)

**Closed by cw118** 2023-04-06 21:21 UTC
Labels: l10n-fr, needs triage
