### ISSUE TITLE
Splice() script does not run

### ISSUE THREAD

**Issue by Zakhiel50** [mdn/translated-content#12226] opened 2023-03-16 12:23 UTC
### MDN URL

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/splice

### What specific section or headline is this issue about?

Exemple interactif

### What information was incorrect, unhelpful, or incomplete?

the script does not run
![spliceScriptNoRun](https://user-images.githubusercontent.com/102024095/225615992-e80af974-5ddd-479f-b5fa-fbaa0d6ad093.jpg)

### What did you expect to see?

the interactive example.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `fr/web/javascript/reference/global_objects/array/splice`
* MDN URL: https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Array/splice
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/fr/web/javascript/reference/global_objects/array/splice/index.md
* Last commit: https://github.com/mdn/translated-content/commit/d5befc946d049e52a2a1b49a46cefff26617b918
* Document last modified: 2022-11-28T08:53:19.000Z

</details>

**Comment by cw118** [comment] 2023-03-16 22:28
Hi @Zakhiel50, thank you for the report! If this is still an issue could you please provide more information? The interactive example works for me in multiple browsers on different devices.

**Comment by cw118** [comment] 2023-03-26 16:55
I checked again and the interactive example still works for me, so I will close this for now. If the issue is still present, please provide more details and this can be reopened :)

**Closed by cw118** 2023-03-26 16:55 UTC
Labels: l10n-fr, needs info

**Comment by Zakhiel50** [comment] 2023-03-26 16:58
Hi, it's okay for me too.
I don't know what could have happened.
