### ISSUE TITLE
Issue with "Курсор": (missed example images)

### ISSUE THREAD

**Issue by ShlemenKirill** [mdn/translated-content#3925] opened 2022-01-31 13:04 UTC
MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/cursor

#### What information was incorrect, unhelpful, or incomplete?
Missed examples images
![image](https://user-images.githubusercontent.com/15968471/151798242-5d30816d-84f3-4321-86c7-dc4d5a84e8dd.png)

#### Specific section or headline?
Изменение размера, прокручивание (скроллинг)

#### What did you expect to see?
Example images

#### Did you test this? If so, how?
![image](https://user-images.githubusercontent.com/15968471/151798382-5ded56cd-0f60-4d62-80ce-e5ee9640f8e5.png)

<details>
<summary>MDN Content page report details</summary>

* Folder: `ru/web/css/cursor`
* MDN URL: https://developer.mozilla.org/ru/docs/Web/CSS/cursor
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/ru/web/css/cursor/index.html
* Last commit: https://github.com/mdn/translated-content/commit/509c3fd223e0370e1ae2adc937c67b336d85df87
* Document last modified: 2022-01-30T16:28:58.000Z

</details>

**Comment by SphinxKnight** [comment] 2022-01-31 15:43
any fix for this could benefit from https://github.com/mdn/yari/pull/5215

**Comment by cw118** [comment] 2022-01-31 15:45
I might be mistaken but it looks like the issue is caused by wrong file names, I'm not seeing any live samples on the page

**Closed** 2022-02-03 13:43 UTC
Labels: l10n-ru
