### ISSUE TITLE
Issue with "Protótipos de objetos": (short summary here please)

### ISSUE THREAD

**Issue by aaamenezes** [mdn/translated-content#2961] opened 2021-11-04 12:30 UTC
MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/Objects/Object_prototypes

#### What information was incorrect, unhelpful, or incomplete?
In portuguese version of this article, in 'O que é o "this"?' section, it says 'efere-se' instead of 'refere-se'

#### Specific section or headline?
https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/Objects/Object_prototypes#uma_linguagem_baseada_em_prot%C3%B3tipos

#### What did you expect to see?
'refere-se' instead of 'efere-se'

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `pt-br/learn/javascript/objects/object_prototypes`
* MDN URL: https://developer.mozilla.org/pt-BR/docs/Learn/JavaScript/Objects/Object_prototypes
* GitHub URL: https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/javascript/objects/object_prototypes/index.html
* Last commit: https://github.com/mdn/translated-content/commit/db721fb507ce6855783e31af7ea84920f7af8ea1
* Document last modified: 2021-11-02T18:06:43.000Z

</details>

**Comment by cw118** [comment] 2022-03-12 15:36
Thanks for reporting! I believe this has been fixed by #3352.

**Comment by cw118** [comment] 2022-03-12 15:39
My bad, reopening since the issue is still there at [line 35 of the file](https://github.com/mdn/translated-content/blob/main/files/pt-br/learn/javascript/objects/object_prototypes/index.html#L35).

**Comment by cw118** [comment] 2022-03-26 16:25
Taken care of in #4665

**Closed by cw118** 2022-03-26 16:25 UTC
Labels: good first issue, l10n-pt-br
